// <auto-generated />
using System;
using DAL.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Db.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221211210707_Change CheckersGame.PlayerId to PlayerName")]
    partial class ChangeCheckersGamePlayerIdtoPlayerName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Domain.CheckersGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BlackAiType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BlackPlayerName")
                        .HasColumnType("TEXT");

                    b.Property<int>("CheckersRulesetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WhiteAiType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WhitePlayerName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Winner")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CheckersRulesetId");

                    b.ToTable("CheckersGames");
                });

            modelBuilder.Entity("Domain.CheckersRuleset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BlackMovesFirst")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanCaptureBackwards")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanCaptureBackwardsDuringMultiCapture")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FlyingKings")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MustCapture")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Saved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CheckersRulesets");
                });

            modelBuilder.Entity("Domain.CheckersState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlackMoves")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CheckersGameId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastMoveState")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastMovedToX")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastMovedToY")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerializedGamePieces")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WhiteMoves")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CheckersGameId");

                    b.ToTable("CheckersStates");
                });

            modelBuilder.Entity("Domain.CheckersGame", b =>
                {
                    b.HasOne("Domain.CheckersRuleset", "CheckersRuleset")
                        .WithMany()
                        .HasForeignKey("CheckersRulesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckersRuleset");
                });

            modelBuilder.Entity("Domain.CheckersState", b =>
                {
                    b.HasOne("Domain.CheckersGame", null)
                        .WithMany("CheckersStates")
                        .HasForeignKey("CheckersGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.CheckersGame", b =>
                {
                    b.Navigation("CheckersStates");
                });
#pragma warning restore 612, 618
        }
    }
}
